### ISSUE TITLE
WebUI with multiple config files, multiuser

### ISSUE THREAD

**Issue by rhoerbe** [identinetics/saml2test2#26]
Objective: use the webui.samltest.fed-lab.org for different test targets by multiple users.

Procedure:
Each new session (REST or browser) will store its log files and persist its results with a key combining email + url of github config project.

**Comment by rhoerbe** [comment]
Requires to upload config files as JSON

**Comment by thomaswar** [comment]
Done.
See wb_idp_test.adoc
