### ISSUE TITLE
Separating code and config data

### ISSUE THREAD

**Issue by rhoerbe** [identinetics/saml2test2#4]
configuration should be isolated from code. Either in a directory, better in a separate project. Deployers should copy the config project, and install saml2test2 from pypi.

**Comment by rhoerbe** [comment]
Resolved in principle with new ConfigLoader.
TODO: move exampleconfig to new project saml2test2.config.abstract && fork it to saml2test2.config.idp1SamltestFed-labOrg

**Comment by thomaswar** [comment]
Done.
